POST http://localhost:3001/sets
Content-Type: application/json

{
    "title": "1",
    "description": "Aasdf",
    "cardList": [
        {"front": "e", "back": "d"},
        {"front": "test", "back": "again"}
    ],
    "username": "el pato"
}